### ISSUE TITLE
Sonuç buluyor ama göstermiyor

### ISSUE THREAD

**Issue by liberteryen** [Worlex0/php-and-mysql-search-console#1]
![resim](https://user-images.githubusercontent.com/84645312/211411464-52f82ae8-ff8b-4d14-9eca-7571635e3517.png)
Böyle boş gösteriyor

**Comment by BurakAydmrr** [comment]
veritabanını yüklediniz mi ? yükledi iseniz birkaç veri ekleyin

**Comment by liberteryen** [comment]
İçi dolu bir veritbanı var bende. banlı oyuncuların olduğu bi liste. senin kodun doğru sayıyı buluyor ama yazıları göstermiyor. sorun bu. kolay gelsin

**Comment by BurakAydmrr** [comment]
`SELECT * FROM table_name WHERE  column name  LIKE '%$search%'`
buradaki bulunan table_name -column name doğru girdiğinden emin ol ve satır 63 de bulunan
` <?php echo $i . "-" . $row['title']; ?>` "title" yazan yeri kendi veri tabanındaki ad ile değiştir sorun düzelicektir.

**Comment by liberteryen** [comment]
En kısa zamanda yapacağım. Sonucu bildiririm. :)

**Comment by BurakAydmrr** [comment]
bekliyorum kolay gelsin :)

**Comment by liberteryen** [comment]
Oldu çok teşekkür ederim. 2 bir isteğim şu sorundan bağımsız veritabanında ismi id'i ve banlandığı tarih var. 63.satırdaki title kısmını 1 değilde 3 sonuç verecek şekilde değiştirebiliyor muyuz?

**Comment by BurakAydmrr** [comment]
` <?php echo $i . "-" . $row['title']; ?>` tabi bu kodu "title" değil de "tarih" gibi çoğaltabilirisniz.
projeyi beğendiysen star atarsan sevinirim 💯

**Comment by liberteryen** [comment]
Herşey okey ama biraz geç sürüyor sorgular. Bunu hızlandırmanın yolu var mı? Emeğiniz ve yardımınız için teşekkürler.

**Comment by BurakAydmrr** [comment]
Rica ederim. Veritabanında veriniz çok olduğu için olabilir ve birden fazla arama yaptığınız için yavaş arama yapmasına etki eden bir durumdur.
